language: ruby
sudo: false

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

bundler_args: --without development --jobs 3 --retry 3
cache: bundler

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-1.7
  - jruby-9.1
  - jruby-head
  - rbx-2
  - rbx-3

matrix:
  allow_failures:
    - rvm: 2.5
    - rvm: ruby-head
    - rvm: jruby-1.7
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-3
  fast_finish: true
