language: ruby
sudo: false

env:
  global:
    - JRUBY_OPTS="-Xcli.debug=true --debug"

bundler_args: --without development --jobs 3 --retry 3
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-1.7
  - jruby-9.1.15.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-1.7
    - rvm: jruby-head
  fast_finish: true
